version: "3.9"
services:
        django:
                build: .
                environment:
                        SEC_KEY: "${SEC_KEY}"
                volumes:
                        - ./:/app
                command: python3 manage.py runserver  0.0.0.0:8000
                ports:
                        - "8000:8000"
        redis:
                image: "redis:alpine"
